### ISSUE TITLE
request for vignette

### ISSUE THREAD

**Issue by mikejiang** [borishejblum/NPflow#18]
I wonder if there is some sort of vignette or tutorial that demonstrates the typical workflow of the main functions provided by the package. Right now I don't have the clue where to start since there are dozens functions written in the source code and it is not clear where is the main entry API.
Here is the data I am trying to work on
```r
#load the gated data
library(flowWorkspace)
dataDir <- system.file("extdata",package="flowWorkspaceData")
gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))

#get CD3+ cells
fr <- getData(gs[[1]], "CD3+")
mat <- exprs(fr)[, c(5, 7)]

#visualize it in cd4, cd8 dimensions
library(hexbin)
plot(hexbin(mat))
```
![image](https://cloud.githubusercontent.com/assets/1385649/24572505/1763547c-162e-11e7-87e7-b678ea2c5472.png)

And as far as I understand that `NPflow` is able to return the 4 clusters (4 quadrants in the plot), right?

**Comment by borishejblum** [comment]
Hi Mike,

First, **thank you** very much for your interest in NPflow. 

Unfortunately there isn't any tutorial or vignette for the package at the moment, although we hope to be able to devote time to write one in the near future...

The main function of the package is _DPMproc_. 
I have updated its documentation so that the examples are (hopefully) more helpful, in the last commits (branch CRANrelease). It should be available on CRAN in the next couple days.

Concerning your data, NPflow will estimate the posterior distribution of the data clustering (not necessarily 4 clusters, it depends of the data).

Best, 
Boris

**Comment by mikejiang** [comment]
I followed your newly added example
```r
# Define hyperprior
hyperG0 <- list()
hyperG0[["mu"]] <- rep(0,d)
hyperG0[["kappa"]] <- 0.001
hyperG0[["nu"]] <- d+2
hyperG0[["lambda"]] <- diag(d)

z <- t(mat)
MCMCsample_n <- DPMpost(data=z, hyperG0=hyperG0, N=500,  distrib="gaussian", diagVar=FALSE  ,ncores = 4 , doPlot = F )
```
It takes `6` minutes to finish `DPMpost` after some parameter tunning:
* disabling plotting
* reducing iteration from `2k` to `500` 
* parallel in `10` cores,

But when I moved on to `Summarizing` step, it seems to be running for ever ( I waited for 1 hour with nothing)
```r
> s <- summary(MCMCsample_n, burnin = 1500, thin=5, lossFn = "Binder")
Estimating posterior similarity matrix...
(this may take some time, complexity in O(n^2))
```
This  sample size is relatively small (`50k events`) compared to the other real data sets, I wonder if you have any further advice for me so that I can get the `NPflow` job done in a more timely manner.

@raphg

**Comment by borishejblum** [comment]
Hi Mike,

First, a disclaimer : we are aware that NPflow is not especially fast, and we are doing our best to improve its computational speed. 

This being said, your summary statement is obviously wrong: you specify a `burnin` of `1500` where you have only `500` MCMC iterations... This should throw an error, and it is surprising that it did not (it does error when I run your above code). 

To try to speed up your computations a little more you can further customize the following arguments:
1.  In the `DPMpost` call
- set `diagVar = TRUE`
- reduce the initial number of clusters `nbclust_init` (although not too much)
2. In the `summary` call, set `lossFn="F-measure"` (which does not need to compute the similarity matrices to provide a point estimate).

But be careful, with this few iterations (500) on over 50k observations, I don't expect the MCMC to have converged (you can check that by running 2 chains).

Best,
Boris

**Comment by mikejiang** [comment]
I `subsample` the data into size of `5k` rows
```r
#' subsample the data to reduce the computation
n <- nrow(mat)
ind <- sample(1:n, size = 0.1*n)
mat <- mat[ind, ]
```
 and adjust the parameters as you suggested
```r
MCMCsample_n <- DPMpost(data=z, hyperG0=hyperG0
                        , N=1000, ncluster_init =10 
                        , distrib="gaussian", diagVar=TRUE
                        , ncores = 10 , doPlot = F
                        )
```
Now it takes `18` seconds to finish `DPMpost` call, but I am still stuck at the `summary`, which doesn't seem to be able to handle `5k` observations
```r
s <- summary(MCMCsample_n, burnin = 500, thin=5, lossFn = "F-measure")
```

**Comment by borishejblum** [comment]
Hi Mike, 

`summary.DPMMclust` is perfectly capable of handling 100 partitions of 5,000 observations (`(N - burnin/thin`, so in your case (1000 - 500)/5 = 100), and on my laptop the whole script runs in less than 2min (I don't think parallelisation is critically useful at that scale):
```r
rm(list=ls())

#load the gated data
library(flowWorkspace)
dataDir <- system.file("extdata", package="flowWorkspaceData")
gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))

#get CD3+ cells
fr <- getData(gs[[1]], "CD3+")
mat <- exprs(fr)[, c(5, 7)]

#visualize it in cd4, cd8 dimensions
library(hexbin)
plot(hexbin(mat))

# Define hyperprior
d <- ncol(mat)
hyperG0 <- list()
hyperG0[["mu"]] <- colMeans(mat) # Empirical Bayes prior
hyperG0[["kappa"]] <- 0.001
hyperG0[["nu"]] <- d+2
hyperG0[["lambda"]] <- diag(diag(var(mat))/3) # Empirical Bayes prior

#' subsample the data to reduce the computation
n <- nrow(mat)
ind <- sample(1:n, size = 0.1*n)
mat <- mat[ind, ]

z <- t(mat)
library(NPflow)
MCMCsample_n <- DPMpost(data = z, hyperG0 = hyperG0, 
                        N = 1000, nbclust_init = 10 ,
                        distrib = "gaussian", diagVar = TRUE,
                        doPlot = FALSE)
s <- summary(MCMCsample_n, burnin = 500, thin = 5, lossFn = "F-measure")
```

Boris

**Comment by mikejiang** [comment]
Looks like you have the more powerful CPU than I do, I am still spending `8` min on it even when I further thrink the size of sample
```r
 nrow(mat)
[1] 2724
> s <- summary(MCMCsample_n, burnin = 500, thin=5, lossFn = "F-measure")
Estimating posterior F-measures matrix...
(this may take some time, complexity in O(n^2))
DONE!
> time3 <- Sys.time()
> time3 - time2
Time difference of 8.024548 mins
```
Anyway, now the plotting failed
```r
> plot(s)
Plotting point estimate (may take a few sec)... 
 Show Traceback
 
 Rerun with Debug
 Error in match.names(clabs, names(xi)) : 
  names do not match previous names 
```
Can you explain how to interpret and use the results from `DPMpost`, my goal is to get cells from top left and bottom right clusters respectively

**Comment by mikejiang** [comment]
The error was probably due to some bug in the ellipse plotting 
```r
> traceback()
8: stop("names do not match previous names")
7: match.names(clabs, names(xi))
6: rbind(deparse.level, ...)
5: rbind(ellipse95_esp, cbind(as.data.frame(ellipse(U_corr2plot_g, 
       scale = sqrt(diag(U_Sigma2plot_esp)), centre = U_mu2plot[, 
           g], level = 0.95)), Cluster = as.character(glabel))) at plot_DPM.R#212
4: plot_DPM(z = x$data, c = x$point_estim$c_est, i = ind + x$burnin, 
       alpha = x$alpha[ind], U_SS = x$U_SS_list[[ind]], gg.add = gg.add, 
       ...) at summary.DPMMclust.R#160
3: plot.summaryDPMMclust(s)
2: plot(s)
```
And I managed to skip ellipse plotting (currently it is not possible through the API, I will push the fix in a minute), here is the plot
![image](https://cloud.githubusercontent.com/assets/1385649/24777731/9268fd14-1adb-11e7-86f3-fb09e663c08b.png)

So, again, my question are
* Is there an existing API allows me to retrieve these cluster ID/membership for each cell events?
* how do I merge these small clusters into two major clusters (top left and bottom right are the actual pops of interest)

**Comment by chariff** [comment]
Hello Mike,

 You'd rather use the skew-t distribution as it will result in a smaller
number of clusters. Also, you must increase the number of iterations, the
burn in period and the thining. Try the code bellow and let us know the
results. Also you can find the membership for each cell events in
s$point_estim$c_est.


MCMCsample_n <- DPMpost(data=z, hyperG0=hyperG0
                        , N=5000, ncluster_init =10
                        , distrib="skewt", diagVar=TRUE
                        , doPlot = F
)s <- summary(MCMCsample_n, burnin = 4000, thin=20, lossFn = "F-measure")


It should give a much better result.

Chariff


2017-04-07 0:16 GMT+02:00 Mike Jiang <notifications@github.com>:

**Comment by chariff** [comment]
Hello Mike,

You'd rather use the skew-t distribution as it will result in a smaller
number of clusters. Also, you must increase the number of iterations, the
burn in period and the thining. FInally, it's probably helpful to start with a it more initial clusters.

Try the code bellow and let us know the results. Also you can find the membership for each cell events in `s$point_estim$c_est`.

```r
MCMCsample_n <- DPMpost(data=z, hyperG0=hyperG0,
N=5000, ncluster_init =15,
distrib="skewt", diagVar=TRUE,
doPlot = FALSE
)
s <- summary(MCMCsample_n, burnin = 4000, thin=20, lossFn = "F-measure")
plot(s)
s$point_estim$c_est
```

It should give a much better result.

Chariff

**Comment by chariff** [comment]
Hello Mike,

You'd rather use the skew-t distribution as it will result in a smaller
number of clusters. Also, you must increase the number of iterations, the
burn in period and the thining. Finally, it's probably helpful to start with a bit more initial clusters.

Try the code bellow and let us know the results. Also you can find the membership for each cell events in `s$point_estim$c_est`.

```r

hyperG0 <- list()
hyperG0[["b_xi"]] <- colMeans(mat)
hyperG0[["b_psi"]] <- rep(0, d)
hyperG0[["kappa"]] <- 0.001
hyperG0[["D_xi"]] <- 100
hyperG0[["D_psi"]] <- 100
hyperG0[["nu"]] <- d + 1
hyperG0[["lambda"]] <- diag(apply(z, MARGIN = 1, FUN = var))

MCMCsample_st <- DPMpost(data = z, hyperG0 = hyperG0,
                        N = 5000, nbclust_init = 15,
                        distrib = "skewt", diagVar = FALSE,
                        doPlot = FALSE
)
s <- summary(MCMCsample_st, burnin = 4000, thin = 20, lossFn = "F-measure")
s
plot(s)
s$point_estim$c_est
```

It should give a much better result.

Chariff

**Comment by mikejiang** [comment]
http://rpubs.com/wjiang2/267708
Here is the example or using `NPflow` on `7` dimensions and I was trying to find out if some of these clusters represent the biological meaningful cell populations defined in traditional hierarchical `2d` gating.

For the sake of computation, I used `5%` of original data and wonder if there is way to apply the model to the original data based on the model fitted from subsampled data?

**Comment by borishejblum** [comment]
Hi Mike,

NPflow does not provide a classification rule for new data, as it directly estimates the posterior distribution of the data partition. 

Also, I don't recommend basic subsampling for flow cytometry data, as small cell subpopulations will become even harder to identify while important subpopulations will appear artificially dispersed. For more info you can read more on this issue in Manolopoulou, Chan & West (2010), Selection Sampling from Large Data Sets for Targeted Inference in Mixture Modeling, _Bayesian Analysis_ 5(3):1–22.

That being said, you could always take the parametric mixture model associated with the partition posterior point-estimate, and compute class membership probabilities for new data. However this is not implemented in NPflow, as it is intended to perform inference on the complete data. You can also look at the sequential posterior approximation strategy if you would rather split up your data.

Boris
