### ISSUE TITLE
Error in if (class(B) == "try-error") { : the condition has length > 1 for skew-t distribuiton

### ISSUE THREAD

**Issue by w3683558** [borishejblum/NPflow#24]
When I tried the  Example in 2 dimensions with skew-t distributions (page 50-51 on the CRAN Reference manual), a error message pops up: 
Error in if (class(B) == "try-error") { : the condition has length > 1
 
I used the function below:
DPMpost(data=z, hyperG0=hyperG0, N=2000,
distrib="skewt")

It looks like this function does not work with the newer version of the R (https://stackoverflow.com/questions/73100875/package-ceases-to-work-due-to-if-error-condition-has-length-1). I really like the method in the package and I hope you can help me with this. Thank you!

**Comment by borishejblum** [comment]
This has been fixed in version 0.13.4
